# Generated by Django 3.1.1 on 2020-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('encrypted_message', models.CharField(blank=True, max_length=200, null=True)),
                ('hashed_message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
